/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountModal: typeof import('./src/components/AccountModal.vue')['default']
    AnniversaryBanner: typeof import('./src/components/AnniversaryBanner.vue')['default']
    AppContainer: typeof import('./src/components/AppContainer.vue')['default']
    AppProvider: typeof import('./src/components/AppProvider/index.vue')['default']
    Authentication: typeof import('./src/components/Authentication.vue')['default']
    Blank: typeof import('./src/components/Blank.vue')['default']
    CalendarView: typeof import('./src/components/CalendarView.vue')['default']
    DateTimePickerModal: typeof import('./src/components/DateTimePickerModal.vue')['default']
    HelpDialog: typeof import('./src/components/HelpDialog.vue')['default']
    MobileDateRangePicker: typeof import('./src/components/MobileDateRangePicker.vue')['default']
    NoteActions: typeof import('./src/components/NoteActions.vue')['default']
    NoteEditor: typeof import('./src/components/NoteEditor.vue')['default']
    NoteItem: typeof import('./src/components/NoteItem.vue')['default']
    NoteItemSkeleton: typeof import('./src/components/NoteItemSkeleton.vue')['default']
    NoteList: typeof import('./src/components/NoteList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    TheDoc: typeof import('./src/components/TheDoc.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter/index.vue')['default']
    TrashModal: typeof import('./src/components/TrashModal.vue')['default']
  }
}
