// src/utils/weatherMap.ts

export const cityMap: Record<string, string> = {
  'Beijing': '北京',
  'Shanghai': '上海',
  'Guangzhou': '广州',
  'Shenzhen': '深圳',
  'Hangzhou': '杭州',
  'Chengdu': '成都',
  'Wuhan': '武汉',
  'Nanjing': '南京',
  'Tianjin': '天津',
  'Chongqing': '重庆',
  "Xi'an": '西安',
  'Changsha': '长沙',
  'Zhengzhou': '郑州',
  'Fuzhou': '福州',
  'Xiamen': '厦门',
  'Ningbo': '宁波',
  'Suzhou': '苏州',
  'Qingdao': '青岛',
  'Jinan': '济南',
  'Shenyang': '沈阳',
  'Dalian': '大连',
  'Harbin': '哈尔滨',
  'Kunming': '昆明',
  'Hefei': '合肥',
  'Nanchang': '南昌',
  'Urumqi': '乌鲁木齐',
  'Shijiazhuang': '石家庄',
  'Tangshan': '唐山',
  'Qinhuangdao': '秦皇岛',
  'Handan': '邯郸',
  'Xingtai': '邢台',
  'Baoding': '保定',
  'Zhangjiakou': '张家口',
  'Chengde': '承德',
  'Cangzhou': '沧州',
  'Langfang': '廊坊',
  'Hengshui': '衡水',
  'Taiyuan': '太原',
  'Datong': '大同',
  'Yangquan': '阳泉',
  'Changzhi': '长治',
  'Jincheng': '晋城',
  'Shuozhou': '朔州',
  'Jinzhong': '晋中',
  'Yuncheng': '运城',
  'Xinzhou': '忻州',
  'Linfen': '临汾',
  'Luliang': '吕梁',
  'Hohhot': '呼和浩特',
  'Baotou': '包头',
  'Wuhai': '乌海',
  'Chifeng': '赤峰',
  'Tongliao': '通辽',
  'Ordos': '鄂尔多斯',
  'Hulunbuir': '呼伦贝尔',
  'Bayannur': '巴彦淖尔',
  'Ulanqab': '乌兰察布',
  'an League': '兴安盟',
  'Xilingol League': '锡林郭勒盟',
  'Alxa League': '阿拉善盟',
  'Anshan': '鞍山',
  'Fushun': '抚顺',
  'Benxi': '本溪',
  'Dandong': '丹东',
  'Jinzhou': '锦州',
  'Yingkou': '营口',
  'Fuxin': '阜新',
  'Liaoyang': '辽阳',
  'Panjin': '盘锦',
  'Tieling': '铁岭',
  'Chaoyang': '朝阳',
  'Huludao': '葫芦岛',
  'Changchun': '长春',
  'Jilin': '吉林',
  'Siping': '四平',
  'Liaoyuan': '辽源',
  'Tonghua': '通化',
  'Baishan': '白山',
  'Songyuan': '松原',
  'Baicheng': '白城',
  'Yanbian Korean Autonomous Prefecture': '延边朝鲜族自治州',
  'Qiqihar': '齐齐哈尔',
  'Jixi': '鸡西',
  'Hegang': '鹤岗',
  'Shuangyashan': '双鸭山',
  'Daqing': '大庆',
  'Yichun': '伊春',
  'Jiamusi': '佳木斯',
  'Qitaihe': '七台河',
  'Mudanjiang': '牡丹江',
  'Heihe': '黑河',
  'Suihua': '绥化',
  'anling Prefecture': '大兴安岭地区',
  'Wuxi': '无锡',
  'Xuzhou': '徐州',
  'Changzhou': '常州',
  'Nantong': '南通',
  'Lianyungang': '连云港',
  'Huaian': '淮安',
  'Yancheng': '盐城',
  'Yangzhou': '扬州',
  'Zhenjiang': '镇江',
  'Taizhou': '泰州',
  'Suqian': '宿迁',
  'Wenzhou': '温州',
  'Jiaxing': '嘉兴',
  'Huzhou': '湖州',
  'Shaoxing': '绍兴',
  'Jinhua': '金华',
  'Quzhou': '衢州',
  'Zhoushan': '舟山',
  'Lishui': '丽水',
  'Fuyang': '富阳区',
  'Tonglu': '桐庐县',
  'Chun’an': '淳安县',
  'Jiande': '建德市',
  'Lin’an': '临安市',
  'Beilun': '北仑区',
  'Zhenhai': '镇海区',
  'Yuyao': '余姚市',
  'Cixi': '慈溪市',
  'Fenghua': '奉化区',
  'Longwan': '龙湾区',
  'Ouhai': '瓯海区',
  'Ruian': '瑞安市',
  'Pingyang': '平阳县',
  'Cangnan': '苍南县',
  'Yueqing': '乐清市',
  'Nanxun': '南浔区',
  'Deqing': '德清县',
  'Anji': '安吉县',
  'Haining': '海宁市',
  'Pinghu': '平湖市',
  'Haiyan': '海盐县',
  'Changxing': '长兴县',
  'Lengshuijiang': '临兴县',
  'Yuecheng': '越城区',
  'Keqiao': '柯桥区',
  'Shangyu': '上虞区',
  'Xinchang': '新昌县',
  'Dinghai': '定海区',
  'Putuo': '普陀区',
  'Daishan': '岱山县',
  'Shengsi': '嵊泗县',
  'Huangyan': '黄岩区',
  'Luqiao': '路桥区',
  'Jiaojiang': '椒江区',
  'Sanmen': '三门县',
  'Yuhuan': '玉环县',
  'Xianju': '仙居县',
  'Tiantai': '天台县',
  'Wenling': '温岭市',
  'Linhai': '临海市',
  'Liandu': '莲都区',
  'Qingtian': '青田县',
  'Longquan': '龙泉市',
  'Jinyun': '缙云县',
  'Suichang': '遂昌县',
  'Songyang': '松阳县',
  'Pan’an': '磐安县',
  'Wuhu': '芜湖',
  'Bengbu': '蚌埠',
  'Huainan': '淮南',
  'Maanshan': '马鞍山',
  'Huaibei': '淮北',
  'Tongling': '铜陵',
  'Anqing': '安庆',
  'Huangshan': '黄山',
  'Chuzhou': '滁州',
  "Lu'an": '六安',
  'Bozhou': '亳州',
  'Chizhou': '池州',
  'Xuancheng': '宣城',
  'Putian': '莆田',
  'Sanming': '三明',
  'Quanzhou': '泉州',
  'Zhangzhou': '漳州',
  'Nanping': '南平',
  'Longyan': '龙岩',
  'Ningde': '宁德',
  'Wenquan': '温泉街道',
  'Jingdezhen': '景德镇',
  'Pingxiang': '萍乡',
  'Jiujiang': '九江',
  'Xinyu': '新余',
  'Yingtan': '鹰潭',
  'Ganzhou': '赣州',
  "Ji'an": '吉安',
  'Shangrao': '上饶',
  'Huangshi': '黄石',
  'Shiyan': '十堰',
  'Yichang': '宜昌',
  'Xiangyang': '襄阳',
  'Ezhou': '鄂州',
  'Jingmen': '荆门',
  'Xiaogan': '孝感',
  'Jingzhou': '荆州',
  'Huanggang': '黄冈',
  'Xianning': '咸宁',
  'Suizhou': '随州',
  'Enshi Tujia and Miao Autonomous Prefecture': '恩施土家族苗族自治州',
  'Zhuzhou': '株洲',
  'Xiangtan': '湘潭',
  'Hengyang': '衡阳',
  'Shaoyang': '邵阳',
  'Yueyang': '岳阳',
  'Changde': '常德',
  'Zhangjiajie': '张家界',
  'Yiyang': '益阳',
  'Chenzhou': '郴州',
  'Yongzhou': '永州',
  'Huaihua': '怀化',
  'Loudi': '娄底',
  'Xiangxi Tujia and Miao Autonomous Prefecture': '湘西土家族苗族自治州',
  'Futian': '福田区',
  'Luohu': '罗湖区',
  'Nanshan': '南山区',
  'Yantian': '盐田区',
  'Baoan': '宝安区',
  'Longgang': '龙岗区',
  'Longhua': '龙华区',
  'Pingshan': '坪山区',
  'Guangming': '光明区',
  'Dapeng': '大鹏新区',
  'Shatou': '沙头街道',
  'Nanyuan': '南园街道',
  'Yuanling': '园岭街道',
  'Huafu': '华富街道',
  'Xiangmihu': '香蜜湖街道',
  'Lianhua': '莲花街道',
  'Meilin': '梅林街道',
  'Huaqiangbei': '华强北街道',
  'Fubao': '福保街道',
  'Huangbei': '黄贝街道',
  'Guiyuan': '桂园街道',
  'Dongmen': '东门街道',
  'Cuizhu': '翠竹街道',
  'Dongxiao': '东晓街道',
  'Nanhu': '南湖街道',
  'Sungang': '笋岗街道',
  'Donghu': '东湖街道',
  'Liantang': '莲塘街道',
  'Qingshuihe': '清水河街道',
  'Nantou': '南头街道',
  'Shahe': '沙河街道',
  'Xili': '西丽街道',
  'Shekou': '蛇口街道',
  'Zhaoshang': '招商街道',
  'Yuehai': '粤海街道',
  'Taoyuan': '桃源街道',
  'Haishan': '海山街道',
  'Meisha': '梅沙街道',
  'Shatoujiao': '沙头角街道',
  'Xin’an': '新安街道',
  'Xixiang': '西乡街道',
  'Fuyong': '福永街道',
  'Shajing': '沙井街道',
  'Songgang': '松岗街道',
  'Hangcheng': '航城街道',
  'Fuhai': '福海街道',
  'Xinqiao': '新桥街道',
  'Yanluo': '燕罗街道',
  'Longcheng': '龙城街道',
  'Henggang': '横岗街道',
  'Buji': '布吉街道',
  'Bantian': '坂田街道',
  'Nanwan': '南湾街道',
  'Pingdi': '坪地街道',
  'Baolong': '宝龙街道',
  'Jihua': '吉华街道',
  'Yuanshan': '园山街道',
  'Minzhi': '民治街道',
  'Dalang': '大浪街道',
  'Guanlan': '观澜街道',
  'Fucheng': '福城街道',
  'Guanhu': '观湖街道',
  'Biling': '碧岭街道',
  'Shijing': '石井街道',
  'Kengzi': '坑梓街道',
  'Longtian': '龙田街道',
  'Maluan': '马峦街道',
  'Gongming': '公明街道',
  'Xinhu': '新湖街道',
  'Fenghuang': '凤凰街道',
  'Yutang': '玉塘街道',
  'Matian': '马田街道',
  'Kuichong': '葵涌街道',
  'Nanao': '南澳街道',
  'Zhuhai': '珠海',
  'Shantou': '汕头',
  'Foshan': '佛山',
  'Shaoguan': '韶关',
  'Zhanjiang': '湛江',
  'Zhaoqing': '肇庆',
  'Jiangmen': '江门',
  'Maoming': '茂名',
  'Huizhou': '惠州',
  'Meizhou': '梅州',
  'Shanwei': '汕尾',
  'Heyuan': '河源',
  'Yuancheng': '源城区',
  'Dongyuan': '东源县',
  'Heping': '和平县',
  'Longchuan': '龙川县',
  'Zijin': '紫金县',
  'Lianping': '连平县',
  'Yuannan': '源南镇',
  'Puqian': '埔前镇',
  'Shangcheng': '上城街道',
  'Xinjiang': '新江街道',
  'Dongpu': '东埔街道',
  'Yuanxi': '源西街道',
  'Gaopugang': '高埔岗街道',
  'Chengdong': '城东街道',
  'Xiantang': '仙塘镇',
  'Dengta': '灯塔镇',
  'Chuantang': '船塘镇',
  'Shuntian': '顺天镇',
  'Shangguan': '上莞镇',
  'Zengtian': '曾田镇',
  'Liucheng': '柳城镇',
  'Yihe': '义合镇',
  'Lankou': '蓝口镇',
  'Huangtian': '黄田镇',
  'Yetan': '叶潭镇',
  'Huancun': '黄村镇',
  'Kanghe': '康禾镇',
  'Xichang': '锡场镇',
  'Xingang': '新港镇',
  'Shuangjiang': '双江镇',
  'Jiantou': '涧头镇',
  'Xinhuilong': '新回龙镇',
  'Banjiang': '半江镇',
  'Zhangxi': '漳溪乡',
  'Yangming': '阳明镇',
  'Daba': '大坝镇',
  'Changtang': '长塘镇',
  'Xiaxie': '下车镇',
  'Shangling': '上陵镇',
  'Yousheng': '优胜镇',
  'Beidun': '贝墩镇',
  'Guzhai': '古寨镇',
  'Pengzhai': '彭寨镇',
  'Heshui': '合水镇',
  'Gongbai': '公白镇',
  'Qingzhou': '青州镇',
  'Miyuan': '浰源镇',
  'Reshui': '热水镇',
  'Dongshui': '东水镇',
  'Lishi': '礼士镇',
  'Linzhai': '林寨镇',
  'Laolong': '老隆镇',
  'Yidu': '义都镇',
  'Tuocheng': '佗城镇',
  'Heshi': '鹤市镇',
  'Huangbu': '黄布镇',
  'Zishi': '紫市镇',
  'Tongqu': '通衢镇',
  'Dengyun': '登云镇',
  'Fengren': '丰稔镇',
  'Sidu': '四都镇',
  'Tiechang': '铁场镇',
  'Longmu': '龙母镇',
  'Tianxin': '田心镇',
  'Lijiao': '黎咀镇',
  'Chiguang': '赤光镇',
  'Huilong': '廻龙镇',
  'Xintian': '新田镇',
  'Chetiian': '车田镇',
  'Yanzhen': '岩镇镇',
  'Shuabugang': '麻布岗镇',
  'Beiling': '贝岭镇',
  'Xiaoao': '细坳镇',
  'Shangping': '上坪镇',
  'Zicheng': '紫城镇',
  'Zhongba': '中坝镇',
  'Longwo': '龙窝镇',
  'Jiuhe': '九和镇',
  'Shangyi': '上义镇',
  'Lantang': '蓝塘镇',
  'Fengan': '凤安镇',
  'Yirong': '义容镇',
  'Guzhu': '古竹镇',
  'Linjiang': '临江镇',
  'Baipu': '柏埔镇',
  'Huangtang': '黄塘镇',
  'Jingzi': '敬梓镇',
  'Shuidun': '水墩镇',
  'Nanling': '南岭镇',
  'Suqiu': '苏区镇',
  'Waxi': '瓦溪镇',
  'Haoyi': '好义镇',
  'Neiguan': '内莞镇',
  'Peitou': '陂头镇',
  'Xishan': '溪山镇',
  'Longjie': '隆街镇',
  'Tianyuan': '田源镇',
  'Youxi': '油溪镇',
  'Zhongxin': '忠信镇',
  'Gaoguan': '高莞镇',
  'Dahu': '大湖镇',
  'Sanjiao': '三角镇',
  'Xiuduan': '绣缎镇',
  'Yangjiang': '阳江',
  'Qingyuan': '清远',
  'Dongguan': '东莞',
  'Zhongshan': '中山',
  'Chaozhou': '潮州',
  'Jieyang': '揭阳',
  'Yunfu': '云浮',
  'Nanning': '南宁',
  'Liuzhou': '柳州',
  'Guilin': '桂林',
  'Wuzhou': '梧州',
  'Beihai': '北海',
  'Fangchenggang': '防城港',
  'Qinzhou': '钦州',
  'Guigang': '贵港',
  'Yulin': '玉林',
  'Baise': '百色',
  'Hezhou': '贺州',
  'Hechi': '河池',
  'Laibin': '来宾',
  'Chongzuo': '崇左',
  'Haikou': '海口',
  'Sanya': '三亚',
  'Sansha': '三沙',
  'Danzhou': '儋州',
  'Zigong': '自贡',
  'Panzhihua': '攀枝花',
  'Luzhou': '泸州',
  'Deyang': '德阳',
  'Mianyang': '绵阳',
  'Guangyuan': '广元',
  'Suining': '遂宁',
  'Neijiang': '内江',
  'Leshan': '乐山',
  'Nanchong': '南充',
  'Meishan': '眉山',
  'Yibin': '宜宾',
  "Guang'an": '广安',
  'Dazhou': '达州',
  "Ya'an": '雅安',
  'Bazhong': '巴中',
  'Ziyang': '资阳',
  'Aba Tibetan and Qiang Autonomous Prefecture': '阿坝藏族羌族自治州',
  'Ganzi Tibetan Autonomous Prefecture': '甘孜藏族自治州',
  'Liangshan Yi Autonomous Prefecture': '凉山彝族自治州',
  'Guiyang': '贵阳',
  'Liupanshui': '六盘水',
  'Zunyi': '遵义',
  'Anshun': '安顺',
  'Bijie': '毕节',
  'Tongren': '铜仁',
  'Qiandongnan Miao and Dong Autonomous Prefecture': '黔东南苗族侗族自治州',
  'Qianxinan Buyi and Miao Autonomous Prefecture': '黔西南布依族苗族自治州',
  'Qiannan Buyi and Miao Autonomous Prefecture': '黔南布依族苗族自治州',
  'Qujing': '曲靖',
  'Yuxi': '玉溪',
  'Baoshan': '保山',
  'Zhaotong': '昭通',
  'Lijiang': '丽江',
  'er': '普洱',
  'Lincang': '临沧',
  'Chuxiong Yi Autonomous Prefecture': '楚雄彝族自治州',
  'Honghe Hani and Yi Autonomous Prefecture': '红河哈尼族彝族自治州',
  'Wenshan Zhuang and Miao Autonomous Prefecture': '文山壮族苗族自治州',
  'Xishuangbanna Dai Autonomous Prefecture': '西双版纳傣族自治州',
  'Dali Bai Autonomous Prefecture': '大理白族自治州',
  'Dehong Dai and Jingpo Autonomous Prefecture': '德宏傣族景颇族自治州',
  'Nujiang Lisu Autonomous Prefecture': '怒江傈僳族自治州',
  'Diqing Tibetan Autonomous Prefecture': '迪庆藏族自治州',
  'Lhasa': '拉萨',
  'Qamdo': '昌都',
  'Shannan': '山南',
  'Xigaze': '日喀则',
  'Nagqu': '那曲',
  'Nyingchi': '林芝',
  'Ngari Prefecture': '阿里地区',
  'Tongchuan': '铜川',
  'Baoji': '宝鸡',
  'Xianyang': '咸阳',
  'Weinan': '渭南',
  "Yan'an": '延安',
  'Hanzhong': '汉中',
  'Shangluo': '商洛',
  'Lanzhou': '兰州',
  'Jiayuguan': '嘉峪关',
  'Jinchang': '金昌',
  'Baiyin': '白银',
  'Tianshui': '天水',
  'Wuwei': '武威',
  'Zhangye': '张掖',
  'Pingliang': '平凉',
  'Jiuquan': '酒泉',
  'Qingyang': '庆阳',
  'Dingxi': '定西',
  'Longnan': '陇南',
  'Linxia Hui Autonomous Prefecture': '临夏回族自治州',
  'Gannan Tibetan Autonomous Prefecture': '甘南藏族自治州',
  'Xining': '西宁',
  'Haidong': '海东',
  'Haibei Tibetan Autonomous Prefecture': '海北藏族自治州',
  'Huangnan Tibetan Autonomous Prefecture': '黄南藏族自治州',
  'Hainan Tibetan Autonomous Prefecture': '海南藏族自治州',
  'Golog Tibetan Autonomous Prefecture': '果洛藏族自治州',
  'Yushu Tibetan Autonomous Prefecture': '玉树藏族自治州',
  'Haixi Mongol and Tibetan Autonomous Prefecture': '海西蒙古族藏族自治州',
  'Yinchuan': '银川',
  'Shizuishan': '石嘴山',
  'Wuzhong': '吴忠',
  'Guyuan': '固原',
  'Zhongwei': '中卫',
  'Karamay': '克拉玛依',
  'Turpan': '吐鲁番',
  'Hami': '哈密',
  'Changji Hui Autonomous Prefecture': '昌吉回族自治州',
  'Bortala Mongol Autonomous Prefecture': '博尔塔拉蒙古族自治州',
  'Bayinguoleng Mongol Autonomous Prefecture': '巴音郭楞蒙古族自治州',
  'Aksu Prefecture': '阿克苏地区',
  'Kizilsu Kirgiz Autonomous Prefecture': '克孜勒苏柯尔克孜族自治州',
  'Kashgar Prefecture': '喀什地区',
  'Hotan Prefecture': '和田地区',
  'Ili Kazakh Autonomous Prefecture': '伊犁哈萨克自治州',
  'Tacheng Prefecture': '塔城地区',
  'Altay Prefecture': '阿勒泰地区',
  'Shihezi': '石河子',
  'Alar': '阿拉尔',
  'Tumxuk': '图木舒克',
  'Wujiaqu': '五家渠',
  'Beitun': '北屯',
  'Tiemenguan': '铁门关',
  'Shuanghe': '双河',
  'Kokdala': '可克达拉',
  'Hong Kong': '香港',
  'Macau': '澳门',
  'Taipei': '台北',
  'Kaohsiung': '高雄',
  'Taichung': '台中',
  'Tainan': '台南',
  'New York': '纽约',
  'Los Angeles': '洛杉矶',
  'San Francisco': '旧金山',
  'London': '伦敦',
  'Paris': '巴黎',
  'Tokyo': '东京',
  'Seoul': '首尔',
  'Bangkok': '曼谷',
  'Singapore': '新加坡',
  'Berlin': '柏林',
  'Sydney': '悉尼',
  'Moscow': '莫斯科',
  'Toronto': '多伦多',
  'Vancouver': '温哥华',
}

export const weatherMap: Record<number, { text: string; icon: string }> = {
  0: { text: '晴朗', icon: '☀️' },
  1: { text: '主要晴天', icon: '🌤️' },
  2: { text: '部分多云', icon: '⛅' },
  3: { text: '多云', icon: '☁️' },
  45: { text: '雾', icon: '🌫️' },
  48: { text: '霜雾', icon: '🌁' },
  51: { text: '毛毛雨', icon: '🌦️' },
  53: { text: '中等毛毛雨', icon: '🌧️' },
  55: { text: '浓密毛毛雨', icon: '🌧️' },
  61: { text: '小雨', icon: '🌧️' },
  63: { text: '中雨', icon: '🌧️' },
  65: { text: '大雨', icon: '🌧️' },
  71: { text: '小雪', icon: '🌨️' },
  73: { text: '中雪', icon: '🌨️' },
  75: { text: '大雪', icon: '❄️' },
  80: { text: '阵雨', icon: '🌦️' },
  81: { text: '中等阵雨', icon: '🌧️' },
  82: { text: '强阵雨', icon: '🌧️' },
  95: { text: '雷雨', icon: '⛈️' },
  96: { text: '雷雨伴小冰雹', icon: '⛈️' },
  99: { text: '雷雨伴大冰雹', icon: '⛈️' },
}
