// src/composables/icon-data.ts

export interface IconInfo {
  icon: string // The emoji character
  keywords: string[]
}

export interface IconCategory {
  category: string
  icons: IconInfo[]
}

// 辅助函数，将关键词转为小写，方便搜索
function processKeywords(icons: Omit<IconInfo, 'keywords'> & { keywords: string[] }[]): IconInfo[] {
  return icons.map(icon => ({
    ...icon,
    keywords: icon.keywords.map(k => k.toLowerCase()),
  }))
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    category: '常用',
    icons: processKeywords([
      { icon: '⭐', keywords: ['star', 'favorite', 'pin', 'xing', '星星', '收藏'] },
      { icon: '🔥', keywords: ['fire', 'hot', 'popular', 'huo', '火', '热门'] },
      { icon: '✨', keywords: ['sparkles', 'shiny', 'shan', '闪亮'] },
      { icon: '📌', keywords: ['pin', 'location', 'ding', '图钉'] },
      { icon: '✅', keywords: ['check', 'tick', 'done', 'wancheng', '完成'] },
      { icon: '❤️', keywords: ['heart', 'love', 'xin', '心', '爱'] },
      { icon: '👍', keywords: ['thumbs up', 'like', 'zan', '赞'] },
      { icon: '💡', keywords: ['idea', 'bulb', 'light', 'dengpao', '灯泡', '想法'] },
      { icon: '📝', keywords: ['note', 'edit', 'write', 'biji', '笔记'] },
      { icon: '📅', keywords: ['date', 'calendar', 'rili', '日历', '日期'] },
      { icon: '⏰', keywords: ['clock', 'time', 'shijian', '时间'] },
      { icon: '💼', keywords: ['work', 'business', 'gongzuo', '工作'] },
      { icon: '🏠', keywords: ['home', 'house', 'jia', '家'] },
      { icon: '💰', keywords: ['money', 'cash', 'qian', '钱'] },
      { icon: '🚀', keywords: ['rocket', 'launch', 'huojian', '火箭'] },
      { icon: '🗑️', keywords: ['trash', 'delete', 'bin', 'shanchu', '删除'] },
      { icon: '🏃', keywords: ['running', 'run', 'sport', 'paobu', '跑步', '运动'] },
      { icon: '💪', keywords: ['strong', 'muscle', 'health', 'liliang', '力量', '健康', '肌肉'] },
      { icon: '🧠', keywords: ['brain', 'mind', 'idea', 'nao', '大脑', '想法', '智慧'] },
      { icon: '💊', keywords: ['pill', 'medicine', 'drug', 'yao', '药', '医疗'] },
    ]),
  },
  {
    category: '对象与符号',
    icons: processKeywords([
      { icon: '✏️', keywords: ['pencil', 'write', 'edit', 'draw', 'qianbi', '铅笔', '写', '编辑', '画'] },
      { icon: '✒️', keywords: ['pen', 'write', 'fountain pen', 'gangbi', '钢笔'] },
      { icon: '📎', keywords: ['paperclip', 'attachment', 'qubiezhen', '回形针', '附件'] },
      { icon: '🔗', keywords: ['link', 'chain', 'lianjie', '链接'] },
      { icon: '🔍', keywords: ['search', 'find', 'magnifying glass', 'sousuo', '搜索', '查找', '放大镜'] },
      { icon: '🔎', keywords: ['search', 'find', 'magnifying glass', 'sousuo', '搜索', '查找', '放大镜'] },
      { icon: '🛡️', keywords: ['shield', 'guard', 'dun', '盾', '保护'] },
      { icon: '⚙️', keywords: ['gear', 'settings', 'chilun', '齿轮', '设置'] },
      { icon: '⚖️', keywords: ['balance', 'scale', 'law', 'tianping', '天平', '法律'] },
      { icon: '🔧', keywords: ['wrench', 'tool', 'banishou', '扳手', '工具'] },
      { icon: '🔨', keywords: ['hammer', 'tool', 'chuizi', '锤子', '工具'] },
      { icon: '🛠️', keywords: ['hammer and wrench', 'tools', 'gongju', '工具'] },
      { icon: '🔑', keywords: ['key', 'password', 'unlock', 'yaoshi', '钥匙', '密码'] },
      { icon: '🔐', keywords: ['locked with key', 'secure', 'suo', '锁'] },
      { icon: '🔒', keywords: ['lock', 'secure', 'suo', '锁'] },
      { icon: '🔓', keywords: ['unlock', 'open', 'jiesuo', '解锁'] },
      { icon: '💰', keywords: ['money bag', 'cash', 'qian', '钱袋'] },
      { icon: '💳', keywords: ['credit card', 'payment', 'xinyongka', '信用卡', '支付'] },
      { icon: '💎', keywords: ['gem', 'diamond', 'zuanshi', '钻石', '宝石'] },
      { icon: '🧾', keywords: ['receipt', 'bill', 'shouju', '收据', '账单'] },
      { icon: '📈', keywords: ['chart increasing', 'graph', 'growth', 'tubiao', '图表', '增长'] },
      { icon: '📉', keywords: ['chart decreasing', 'graph', 'loss', 'tubiao', '图表', '下降'] },
      { icon: '📊', keywords: ['bar chart', 'graph', 'stats', 'tubiao', '图表', '统计'] },
      { icon: '📌', keywords: ['pin', 'location', 'ding', '图钉'] },
      { icon: '📍', keywords: ['round pin', 'location', 'weizhi', '位置'] },
      { icon: '🗑️', keywords: ['trash', 'delete', 'bin', 'shanchu', '删除', '垃圾桶'] },
      { icon: '📅', keywords: ['calendar', 'date', 'rili', '日历', '日期'] },
      { icon: '📆', keywords: ['tear-off calendar', 'date', 'rili', '日历'] },
      { icon: '🗒️', keywords: ['notepad', 'notes', 'bianqian', '便签'] },
      { icon: '🗓️', keywords: ['spiral calendar', 'date', 'rili', '日历'] },
      { icon: '📇', keywords: ['card index', 'contacts', 'mingpian', '名片'] },
      { icon: '📁', keywords: ['file folder', 'directory', 'wenjianjia', '文件夹'] },
      { icon: '📂', keywords: ['open file folder', 'wenjianjia', '文件夹'] },
      { icon: '🗂️', keywords: ['card index dividers', 'organize', 'zhengli', '整理'] },
      { icon: '📋', keywords: ['clipboard', 'paste', 'nianite', '剪贴板', '粘贴'] },
      { icon: '📫', keywords: ['mailbox', 'email', 'youxiang', '邮箱'] },
      { icon: '📪', keywords: ['mailbox', 'email', 'youxiang', '邮箱'] },
      { icon: '📬', keywords: ['mailbox', 'email', 'youxiang', '邮箱'] },
      { icon: '📮', keywords: ['postbox', 'youxiang', '邮箱'] },
      { icon: '📦', keywords: ['package', 'box', 'baoguo', '包裹', '箱子'] },
      { icon: '📝', keywords: ['memo', 'pencil', 'note', 'biji', '笔记'] },
      { icon: '📄', keywords: ['page', 'document', 'wendang', '文档', '页面'] },
      { icon: '📃', keywords: ['page with curl', 'document', 'wendang', '文档'] },
      { icon: '📑', keywords: ['bookmark tabs', 'biaoqian', '标签页'] },
      { icon: '🔖', keywords: ['bookmark', 'save', 'shuqian', '书签'] },
      { icon: '🏷️', keywords: ['label', 'tag', 'biaoqian', '标签'] },
      { icon: '📚', keywords: ['books', 'library', 'shu', '书', '图书馆'] },
      { icon: '📖', keywords: ['open book', 'reading', 'yuedu', '阅读'] },
      { icon: '📗', keywords: ['green book', 'shu', '绿皮书'] },
      { icon: '📘', keywords: ['blue book', 'shu', '蓝皮书'] },
      { icon: '📙', keywords: ['orange book', 'shu', '橙皮书'] },
      { icon: '📔', keywords: ['notebook', 'biji', '笔记本'] },
      { icon: '📓', keywords: ['notebook', 'biji', '笔记本'] },
      { icon: '📒', keywords: ['ledger', 'notebook', 'biji', '笔记本'] },
      { icon: '🖋️', keywords: ['fountain pen', 'write', 'gangbi', '钢笔'] },
      { icon: '🖊️', keywords: ['pen', 'write', 'bi', '笔'] },
      { icon: '🖌️', keywords: ['paintbrush', 'draw', 'art', 'huabi', '画笔'] },
      { icon: '✉️', keywords: ['envelope', 'email', 'mail', 'xinfeng', '信封', '邮件'] },
      { icon: '📧', keywords: ['e-mail', 'email', 'mail', 'youjian', '邮件'] },
      { icon: '📥', keywords: ['inbox', 'download', 'shoujianxiang', '收件箱'] },
      { icon: '📤', keywords: ['outbox', 'upload', 'fajianxiang', '发件箱'] },
      { icon: '📈', keywords: ['chart', 'graph', 'stats', 'tubiao', '图表', '统计'] },
      { icon: '📢', keywords: ['loudspeaker', 'announcement', 'gonggao', '公告'] },
      { icon: '📣', keywords: ['megaphone', 'announcement', 'gonggao', '公告'] },
      { icon: '🔔', keywords: ['bell', 'notification', 'lingdang', '铃铛', '通知'] },
      { icon: '🔕', keywords: ['bell with slash', 'mute', 'jingyin', '静音'] },
      { icon: '⏳', keywords: ['hourglass', 'time', 'shijian', '沙漏', '时间'] },
      { icon: '⌛', keywords: ['hourglass done', 'time', 'shijian', '沙漏', '时间'] },
      { icon: '💡', keywords: ['light bulb', 'idea', 'dengpao', '灯泡', '想法'] },
      { icon: '🔦', keywords: ['flashlight', 'shoudiantong', '手电筒'] },
      { icon: '🔋', keywords: ['battery', 'power', 'dianchi', '电池', '电量'] },
      { icon: '🔌', keywords: ['electric plug', 'power', 'chazuo', '插座'] },
      { icon: '📡', keywords: ['satellite antenna', 'signal', 'xinhao', '信号', '天线'] },
      { icon: '🧭', keywords: ['compass', 'direction', 'zhinanzhen', '指南针', '方向'] },
      { icon: '🧯', keywords: ['fire extinguisher', 'miehuoqi', '灭火器'] },
      { icon: '🧰', keywords: ['toolbox', 'tools', 'gongxiang', '工具箱'] },
      { icon: '🔩', keywords: ['nut and bolt', 'luosi', '螺丝'] },
      { icon: '🧱', keywords: ['brick', 'wall', 'qiang', '墙', '砖'] },
      { icon: '🪑', keywords: ['chair', 'seat', 'yizi', '椅子'] },
      { icon: '🚪', keywords: ['door', 'men', '门'] },
      { icon: '🛏️', keywords: ['bed', 'sleep', 'chuang', '床'] },
    ]),
  },
  {
    category: '人物与表情',
    icons: processKeywords([
      { icon: '😀', keywords: ['grinning face', 'happy', 'smile', 'kaixin', '开心', '笑脸'] },
      { icon: '😃', keywords: ['grinning face with big eyes', 'happy', 'smile', 'kaixin', '开心'] },
      { icon: '😄', keywords: ['grinning face with smiling eyes', 'happy', 'smile', 'kaixin', '开心'] },
      { icon: '😁', keywords: ['beaming face with smiling eyes', 'happy', 'smile', 'kaixin', '开心'] },
      { icon: '😆', keywords: ['grinning squinting face', 'laughing', 'xiao', '笑'] },
      { icon: '😅', keywords: ['grinning face with sweat', 'nervous', 'ganxiao', '尬笑'] },
      { icon: '😂', keywords: ['face with tears of joy', 'laughing', 'happy', 'xiao ku', '笑哭'] },
      { icon: '🤣', keywords: ['rolling on the floor laughing', 'lol', 'xiao', '笑'] },
      { icon: '😊', keywords: ['smiling face with smiling eyes', 'happy', 'blush', 'weixiao', '微笑'] },
      { icon: '😇', keywords: ['smiling face with halo', 'angel', 'tianshi', '天使'] },
      { icon: '🙂', keywords: ['slightly smiling face', 'weixiao', '微笑'] },
      { icon: '🙃', keywords: ['upside-down face', 'sarcastic'] },
      { icon: '😉', keywords: ['winking face', 'wink', 'zhayan', '眨眼'] },
      { icon: '😌', keywords: ['relieved face', 'relax', 'fangsong', '放松'] },
      { icon: '😍', keywords: ['heart eyes', 'love', 'crush', 'aixin', '爱心眼'] },
      { icon: '🥰', keywords: ['smiling face with hearts', 'love', 'crush', 'ai'] },
      { icon: '😘', keywords: ['face blowing a kiss', 'kiss', 'qin', '亲'] },
      { icon: '😗', keywords: ['kissing face', 'kiss', 'qin', '亲'] },
      { icon: '😙', keywords: ['kissing face with smiling eyes', 'kiss', 'qin', '亲'] },
      { icon: '😚', keywords: ['kissing face with closed eyes', 'kiss', 'qin', '亲'] },
      { icon: '😋', keywords: ['face savoring food', 'delicious', 'yum', 'haochi', '好吃'] },
      { icon: '😛', keywords: ['face with tongue', 'playful', 'tiaopi', '调皮'] },
      { icon: '😝', keywords: ['squinting face with tongue', 'playful', 'tiaopi', '调皮'] },
      { icon: '😜', keywords: ['winking face with tongue', 'joke', 'playful', 'tiaopi', '调皮'] },
      { icon: '🤪', keywords: ['zany face', 'crazy', 'fengkuang', '疯狂'] },
      { icon: '🤨', keywords: ['face with raised eyebrow', 'skeptical', 'huaiyi', '怀疑'] },
      { icon: '🧐', keywords: ['face with monocle', 'thinking', 'sikao', '思考'] },
      { icon: '🤓', keywords: ['nerd face', 'geek', 'nerd', 'shudaiizi', '书呆子'] },
      { icon: '😎', keywords: ['smiling face with sunglasses', 'cool', 'ku', '酷'] },
      { icon: '🤩', keywords: ['star-struck', 'excited', 'jingxi', '惊喜'] },
      { icon: '🥳', keywords: ['partying face', 'celebration', 'qingzhu', '庆祝'] },
      { icon: '😏', keywords: ['smirking face', 'smug', 'dexiao', '得笑'] },
      { icon: '😒', keywords: ['unamused face', 'annoyed', 'bufu', '不服'] },
      { icon: '😞', keywords: ['disappointed face', 'sad', 'shiwang', '失望'] },
      { icon: '😔', keywords: ['pensive face', 'sad', 'chensi', '沉思'] },
      { icon: '😟', keywords: ['worried face', 'nervous', 'danxin', '担心'] },
      { icon: '😕', keywords: ['confused face', 'kunhuo', '困惑'] },
      { icon: '🙁', keywords: ['slightly frowning face', 'sad', 'nanguo', '难过'] },
      { icon: '☹️', keywords: ['frowning face', 'sad', 'nanguo', '难过'] },
      { icon: '😣', keywords: ['persevering face', 'struggling', 'tongku', '痛苦'] },
      { icon: '😖', keywords: ['confounded face', 'tongku', '痛苦'] },
      { icon: '😫', keywords: ['tired face', 'lei', '累'] },
      { icon: '😩', keywords: ['weary face', 'tired', 'lei', '累'] },
      { icon: '🥺', keywords: ['pleading face', 'begging', 'keliian', '可怜'] },
      { icon: '😢', keywords: ['crying face', 'sad', 'ku', '哭'] },
      { icon: '😭', keywords: ['loudly crying face', 'sad', 'ku', '大哭'] },
      { icon: '😤', keywords: ['face with steam from nose', 'angry', 'shengqi', '生气'] },
      { icon: '😠', keywords: ['angry face', 'mad', 'shengqi', '生气'] },
      { icon: '😡', keywords: ['pouting face', 'angry', 'mad', 'shengqi', '生气'] },
      { icon: '🤬', keywords: ['face with symbols on mouth', 'swearing', 'ma', '骂'] },
      { icon: '🤯', keywords: ['exploding head', 'mind blown', 'zhenjing', '震惊'] },
      { icon: '😳', keywords: ['flushed face', 'embarrassed', 'haixiu', '害羞'] },
      { icon: '🥵', keywords: ['hot face', 'sweating', 're', '热'] },
      { icon: '🥶', keywords: ['cold face', 'freezing', 'leng', '冷'] },
      { icon: '😱', keywords: ['face screaming in fear', 'shock', 'jingkong', '惊恐'] },
      { icon: '😨', keywords: ['fearful face', 'scared', 'haipa', '害怕'] },
      { icon: '😰', keywords: ['anxious face with sweat', 'nervous', 'jiaolv', '焦虑'] },
      { icon: '😥', keywords: ['sad but relieved face', 'sad', 'nanguo', '难过'] },
      { icon: '😓', keywords: ['downcast face with sweat', 'sad', 'nanguo', '难过'] },
      { icon: '🤗', keywords: ['hugging face', 'hug', 'yongbao', '拥抱'] },
      { icon: '🤔', keywords: ['thinking face', 'idea', 'sikao', '思考'] },
      { icon: '🤭', keywords: ['face with hand over mouth', 'oops', 'touxiao', '偷笑'] },
      { icon: '🤫', keywords: ['shushing face', 'quiet', 'anjing', '安静'] },
      { icon: '🤥', keywords: ['lying face', 'lie', 'shuohuang', '说谎'] },
      { icon: '😶', keywords: ['face without mouth', 'silent', 'wuyu', '无语'] },
      { icon: '😐', keywords: ['neutral face', 'meh', 'wuna', '无奈'] },
      { icon: '😑', keywords: ['expressionless face', 'wuna', '无奈'] },
      { icon: '😬', keywords: ['grimacing face', 'awkward', 'ganga', '尴尬'] },
      { icon: '🙄', keywords: ['face with rolling eyes', 'annoyed', 'fanyan', '翻白眼'] },
      { icon: '😯', keywords: ['hushed face', 'surprised', 'jingya', '惊讶'] },
      { icon: '😦', keywords: ['frowning face with open mouth', 'surprised', 'jingya', '惊讶'] },
      { icon: '😧', keywords: ['anguished face', 'surprised', 'jingya', '惊讶'] },
      { icon: '😮', keywords: ['face with open mouth', 'surprised', 'wow', 'jingya', '惊讶'] },
      { icon: '😲', keywords: ['astonished face', 'surprised', 'wow', 'jingya', '惊讶'] },
      { icon: '🥱', keywords: ['yawning face', 'tired', 'dakache', '打哈欠'] },
      { icon: '😴', keywords: ['sleeping face', 'tired', 'shuijiao', '睡觉'] },
      { icon: '🤤', keywords: ['drooling face', 'liukoushui', '流口水'] },
      { icon: '😪', keywords: ['sleepy face', 'tired', 'kun', '困'] },
      { icon: '😵', keywords: ['dizzy face', 'xuan', '晕'] },
      { icon: '🤐', keywords: ['zipper-mouth face', 'secret', 'bimi', '秘密'] },
      { icon: '🥴', keywords: ['woozy face', 'drunk', 'he醉'] },
      { icon: '🤢', keywords: ['nauseated face', 'sick', 'exin', '恶心'] },
      { icon: '🤮', keywords: ['face vomiting', 'sick', 'outu', '呕吐'] },
      { icon: '🤧', keywords: ['sneezing face', 'sick', 'dapenti', '打喷嚏'] },
      { icon: '😷', keywords: ['face with medical mask', 'sick', 'kouzhao', '口罩'] },
      { icon: '🤒', keywords: ['face with thermometer', 'sick', 'fasao', '发烧'] },
      { icon: '🤕', keywords: ['face with head-bandage', 'injured', 'shoushang', '受伤'] },
      { icon: '🤑', keywords: ['money-mouth face', 'rich', 'qian', '钱'] },
      { icon: '🤠', keywords: ['cowboy hat face', 'cowboy', 'niuzai', '牛仔'] },
      { icon: '🥸', keywords: ['disguised face', 'weizhuang', '伪装'] },
      { icon: '👨', keywords: ['man', 'nan', '男'] },
      { icon: '👩', keywords: ['woman', 'nv', '女'] },
      { icon: '🧑', keywords: ['person', 'ren', '人'] },
      { icon: '👧', keywords: ['girl', 'nvhai', '女孩'] },
      { icon: '👦', keywords: ['boy', 'nanhai', '男孩'] },
      { icon: '👶', keywords: ['baby', 'ying-er', '婴儿'] },
      { icon: '👨‍💻', keywords: ['man technologist', 'developer', 'coder', 'chengxuyuan', '程序员'] },
      { icon: '👩‍💻', keywords: ['woman technologist', 'developer', 'coder', 'chengxuyuan', '程序员'] },
      { icon: '👨‍🏫', keywords: ['man teacher', 'professor', 'laoshi', '老师'] },
      { icon: '👩‍🏫', keywords: ['woman teacher', 'professor', 'laoshi', '老师'] },
      { icon: '👨‍🎓', keywords: ['man student', 'graduate', 'xuesheng', '学生', '毕业生'] },
      { icon: '👩‍🎓', keywords: ['woman student', 'graduate', 'xuesheng', '学生', '毕业生'] },
      { icon: '🧑‍⚖️', keywords: ['judge', 'law', 'faguan', '法官'] },
      { icon: '🧑‍🌾', keywords: ['farmer', 'nongmin', '农民'] },
      { icon: '🧑‍🍳', keywords: ['cook', 'chef', 'chushi', '厨师'] },
      { icon: '🧑‍🔧', keywords: ['mechanic', 'repair', 'weixiu', '维修'] },
      { icon: '🧑‍🏭', keywords: ['factory worker', 'gongren', '工人'] },
      { icon: '🧑‍💼', keywords: ['office worker', 'zhiyuan', '职员'] },
      { icon: '🧑‍🔬', keywords: ['scientist', 'kexuejia', '科学家'] },
      { icon: '🧑‍🎨', keywords: ['artist', 'yishujia', '艺术家'] },
      { icon: '🧑‍✈️', keywords: ['pilot', 'feixingyuan', '飞行员'] },
      { icon: '🧑‍🚀', keywords: ['astronaut', 'space', 'yuhangyuan', '宇航员'] },
      { icon: '🧑‍🚒', keywords: ['firefighter', 'xiaofangyuan', '消防员'] },
      { icon: '👮', keywords: ['police officer', 'jingcha', '警察'] },
      { icon: '🕵️', keywords: ['detective', 'zhentan', '侦探'] },
      { icon: '💂', keywords: ['guard', 'weibing', '卫兵'] },
      { icon: '👷', keywords: ['construction worker', 'jianzhugongren', '建筑工人'] },
    ]),
  },
  {
    category: '自然与动物',
    icons: processKeywords([
      { icon: '☀️', keywords: ['sun', 'weather', 'sunny', 'taiyang', '太阳', '晴天'] },
      { icon: '🌞', keywords: ['sun with face', 'sunny', 'taiyang', '太阳'] },
      { icon: '🌕', keywords: ['full moon', 'yueliang', '月亮'] },
      { icon: '🌖', keywords: ['waning gibbous moon', 'yueliang', '月亮'] },
      { icon: '🌗', keywords: ['last quarter moon', 'yueliang', '月亮'] },
      { icon: '🌘', keywords: ['waning crescent moon', 'yueliang', '月亮'] },
      { icon: '🌑', keywords: ['new moon', 'yueliang', '月亮'] },
      { icon: '🌒', keywords: ['waxing crescent moon', 'yueliang', '月亮'] },
      { icon: '🌓', keywords: ['first quarter moon', 'yueliang', '月亮'] },
      { icon: '🌔', keywords: ['waxing gibbous moon', 'yueliang', '月亮'] },
      { icon: '🌙', keywords: ['crescent moon', 'night', 'yewan', '夜晚'] },
      { icon: '🌎', keywords: ['earth globe americas', 'world', 'diqiu', '地球'] },
      { icon: '🌍', keywords: ['earth globe europe-africa', 'world', 'diqiu', '地球'] },
      { icon: '🌏', keywords: ['earth globe asia-australia', 'world', 'diqiu', '地球'] },
      { icon: '⭐', keywords: ['star', 'xing', '星星'] },
      { icon: '🌟', keywords: ['glowing star', 'xing', '星星'] },
      { icon: '🌠', keywords: ['shooting star', 'liuxing', '流星'] },
      { icon: '☁️', keywords: ['cloud', 'weather', 'yun', '云', '阴天'] },
      { icon: '⛅', keywords: ['sun behind cloud', 'weather', 'duoyun', '多云'] },
      { icon: '⛈️', keywords: ['cloud with lightning and rain', 'thunderstorm', 'leizhenyu', '雷阵雨'] },
      { icon: '🌤️', keywords: ['sun behind small cloud', 'weather', 'duoyun', '多云'] },
      { icon: '🌥️', keywords: ['sun behind large cloud', 'weather', 'duoyun', '多云'] },
      { icon: '🌦️', keywords: ['sun behind rain cloud', 'weather', 'taiyangyu', '太阳雨'] },
      { icon: '🌧️', keywords: ['cloud with rain', 'weather', 'yutian', '雨天'] },
      { icon: '🌨️', keywords: ['cloud with snow', 'weather', 'xuetian', '雪天'] },
      { icon: '🌩️', keywords: ['cloud with lightning', 'thunder', 'leidian', '雷电'] },
      { icon: '🌪️', keywords: ['tornado', 'longjuanfeng', '龙卷风'] },
      { icon: '🌫️', keywords: ['fog', 'wu', '雾'] },
      { icon: '🌬️', keywords: ['wind face', 'feng', '风'] },
      { icon: '🌈', keywords: ['rainbow', 'caihong', '彩虹'] },
      { icon: '💧', keywords: ['droplet', 'water', 'shuidi', '水滴'] },
      { icon: '🌊', keywords: ['water wave', 'ocean', 'hailang', '海浪'] },
      { icon: '🔥', keywords: ['fire', 'hot', 'huo', '火'] },
      { icon: '💥', keywords: ['collision', 'boom', 'baozha', '爆炸'] },
      { icon: '❄️', keywords: ['snowflake', 'winter', 'xuehua', '雪花'] },
      { icon: '🌲', keywords: ['evergreen tree', 'shu', '树'] },
      { icon: '🌳', keywords: ['deciduous tree', 'shu', '树'] },
      { icon: '🌴', keywords: ['palm tree', 'yeshu', '椰树'] },
      { icon: '🌱', keywords: ['seedling', 'plant', 'youmiao', '幼苗'] },
      { icon: '🌿', keywords: ['herb', 'leaf', 'caoyao', '草药'] },
      { icon: '☘️', keywords: ['shamrock', 'clover', 'sanyecao', '三叶草'] },
      { icon: '🍀', keywords: ['four leaf clover', 'lucky', 'xinyuncao', '幸运草'] },
      { icon: '🍃', keywords: ['leaf fluttering in wind', 'yezi', '叶子'] },
      { icon: '🍂', keywords: ['fallen leaf', 'autumn', 'luoye', '落叶'] },
      { icon: '🍁', keywords: ['maple leaf', 'autumn', 'fengye', '枫叶'] },
      { icon: '🍄', keywords: ['mushroom', 'mogu', '蘑菇'] },
      { icon: '🌸', keywords: ['cherry blossom', 'flower', 'yinghua', '樱花'] },
      { icon: '🌹', keywords: ['rose', 'flower', 'meigui', '玫瑰'] },
      { icon: '🌺', keywords: ['hibiscus', 'flower', 'hua', '花'] },
      { icon: '🌻', keywords: ['sunflower', 'xiangrikui', '向日葵'] },
      { icon: '🌼', keywords: ['blossom', 'flower', 'hua', '花'] },
      { icon: '🌷', keywords: ['tulip', 'flower', 'yujinxiang', '郁金香'] },
      { icon: '🌵', keywords: ['cactus', 'xianrenzhang', '仙人掌'] },
      { icon: '🌍', keywords: ['earth', 'world', 'diqiu', '地球'] },
      { icon: '🌎', keywords: ['earth', 'world', 'diqiu', '地球'] },
      { icon: '🌏', keywords: ['earth', 'world', 'diqiu', '地球'] },
      { icon: '🌕', keywords: ['moon', 'yueliang', '月亮'] },
      { icon: '🐶', keywords: ['dog face', 'pet', 'gou', '狗'] },
      { icon: '🐱', keywords: ['cat face', 'pet', 'mao', '猫'] },
      { icon: '🐭', keywords: ['mouse face', 'laoshu', '老鼠'] },
      { icon: '🐹', keywords: ['hamster face', 'cangshu', '仓鼠'] },
      { icon: '🐰', keywords: ['rabbit face', 'bunny', 'tuzi', '兔子'] },
      { icon: '🦊', keywords: ['fox face', 'huli', '狐狸'] },
      { icon: '🐻', keywords: ['bear face', 'xiong', '熊'] },
      { icon: '🐼', keywords: ['panda face', 'xiongmao', '熊猫'] },
      { icon: '🐨', keywords: ['koala', 'kaola', '考拉'] },
      { icon: '🐯', keywords: ['tiger face', 'laohu', '老虎'] },
      { icon: '🦁', keywords: ['lion face', 'shizi', '狮子'] },
      { icon: '🐮', keywords: ['cow face', 'niu', '牛'] },
      { icon: '🐷', keywords: ['pig face', 'zhu', '猪'] },
      { icon: '🐸', keywords: ['frog', 'qingwa', '青蛙'] },
      { icon: '🐵', keywords: ['monkey', 'houzi', '猴子'] },
      { icon: '🐔', keywords: ['chicken', 'ji', '鸡'] },
      { icon: '🐧', keywords: ['penguin', 'qie', '企鹅'] },
      { icon: '🐦', keywords: ['bird', 'niao', '鸟'] },
      { icon: '🐤', keywords: ['baby chick', 'xiaoji', '小鸡'] },
      { icon: '🦆', keywords: ['duck', 'yazi', '鸭子'] },
      { icon: '🦅', keywords: ['eagle', 'ying', '鹰'] },
      { icon: '🦉', keywords: ['owl', 'maotouying', '猫头鹰'] },
      { icon: '🦇', keywords: ['bat', 'bianfu', '蝙蝠'] },
      { icon: '🐺', keywords: ['wolf', 'lang', '狼'] },
      { icon: '🐗', keywords: ['boar', 'yezhu', '野猪'] },
      { icon: '🐴', keywords: ['horse', 'ma', '马'] },
      { icon: '🦄', keywords: ['unicorn', 'dushouju', '独角兽'] },
      { icon: '🐝', keywords: ['honeybee', 'mifeng', '蜜蜂'] },
    ]),
  },
  {
    category: '食物与饮料',
    icons: processKeywords([
      { icon: '🍏', keywords: ['green apple', 'fruit', 'pingguo', '苹果'] },
      { icon: '🍎', keywords: ['red apple', 'fruit', 'pingguo', '苹果'] },
      { icon: '🍐', keywords: ['pear', 'fruit', 'li', '梨'] },
      { icon: '🍊', keywords: ['tangerine', 'orange', 'fruit', 'juzi', '橘子'] },
      { icon: '🍋', keywords: ['lemon', 'fruit', 'ningmeng', '柠檬'] },
      { icon: '🍌', keywords: ['banana', 'fruit', 'xiangjiao', '香蕉'] },
      { icon: '🍉', keywords: ['watermelon', 'fruit', 'xigua', '西瓜'] },
      { icon: '🍇', keywords: ['grapes', 'fruit', 'putao', '葡萄'] },
      { icon: '🍓', keywords: ['strawberry', 'fruit', 'caomei', '草莓'] },
      { icon: '🍈', keywords: ['melon', 'fruit', 'gua', '瓜'] },
      { icon: '🍒', keywords: ['cherries', 'fruit', 'yingtao', '樱桃'] },
      { icon: '🍑', keywords: ['peach', 'fruit', 'taozi', '桃子'] },
      { icon: '🥭', keywords: ['mango', 'fruit', 'mangguo', '芒果'] },
      { icon: '🍍', keywords: ['pineapple', 'fruit', 'boluo', '菠萝'] },
      { icon: '🥥', keywords: ['coconut', 'fruit', 'yezi', '椰子'] },
      { icon: '🥝', keywords: ['kiwi fruit', 'mihoutao', '猕猴桃'] },
      { icon: '🍅', keywords: ['tomato', 'vegetable', 'fanqie', '番茄'] },
      { icon: '🍆', keywords: ['eggplant', 'vegetable', 'qiezi', '茄子'] },
      { icon: '🥑', keywords: ['avocado', 'fruit', 'niuyouguo', '牛油果'] },
      { icon: '🥦', keywords: ['broccoli', 'vegetable', 'xilanhua', '西兰花'] },
      { icon: '🥬', keywords: ['leafy green', 'vegetable', 'shucai', '蔬菜'] },
      { icon: '🥒', keywords: ['cucumber', 'vegetable', 'huangggua', '黄瓜'] },
      { icon: '🌶️', keywords: ['hot pepper', 'spicy', 'lajiao', '辣椒'] },
      { icon: '🌽', keywords: ['corn', 'yumi', '玉米'] },
      { icon: '🥕', keywords: ['carrot', 'vegetable', 'huluobo', '胡萝卜'] },
      { icon: '🧄', keywords: ['garlic', 'dasuan', '大蒜'] },
      { icon: '🧅', keywords: ['onion', 'yangcong', '洋葱'] },
      { icon: '🥔', keywords: ['potato', 'vegetable', 'tudou', '土豆'] },
      { icon: '🍠', keywords: ['roasted sweet potato', 'hongshu', '红薯'] },
      { icon: '🥐', keywords: ['croissant', 'bread', 'mianbao', '面包'] },
      { icon: '🥯', keywords: ['bagel', 'bread', 'mianbao', '面包'] },
      { icon: '🍞', keywords: ['bread', 'toast', 'mianbao', '面包'] },
      { icon: '🥖', keywords: ['baguette bread', 'mianbao', '面包'] },
      { icon: '🥨', keywords: ['pretzel', 'mianbao', '面包'] },
      { icon: '🧀', keywords: ['cheese wedge', 'nailao', '奶酪'] },
      { icon: '🥚', keywords: ['egg', 'jidan', '鸡蛋'] },
      { icon: '🍳', keywords: ['cooking', 'egg', 'jian dan', '煎蛋'] },
      { icon: '🧈', keywords: ['butter', 'huangyou', '黄油'] },
      { icon: '🥞', keywords: ['pancakes', 'bing', '饼'] },
      { icon: '🧇', keywords: ['waffle', 'bing', '饼'] },
      { icon: '🥓', keywords: ['bacon', 'peigen', '培根'] },
      { icon: '🥩', keywords: ['cut of meat', 'steak', 'niupai', '牛排'] },
      { icon: '🍗', keywords: ['poultry leg', 'chicken', 'jitui', '鸡腿'] },
      { icon: '🍖', keywords: ['meat on bone', 'rou', '肉'] },
      { icon: '🦴', keywords: ['bone', 'gutou', '骨头'] },
      { icon: '🌭', keywords: ['hot dog', 'regou', '热狗'] },
      { icon: '🍔', keywords: ['hamburger', 'burger', 'hanbao', '汉堡'] },
      { icon: '🍟', keywords: ['french fries', 'shutiao', '薯条'] },
      { icon: '🍕', keywords: ['pizza', 'bisabing', '披萨'] },
      { icon: '🥪', keywords: ['sandwich', 'sanmingzhi', '三明治'] },
      { icon: '🥙', keywords: ['stuffed flatbread'] },
      { icon: '🧆', keywords: ['falafel'] },
      { icon: '🌮', keywords: ['taco'] },
      { icon: '🌯', keywords: ['burrito'] },
      { icon: '🥗', keywords: ['green salad', 'shala', '沙拉'] },
      { icon: '🥘', keywords: ['shallow pan of food'] },
      { icon: '🥫', keywords: ['canned food', 'guantou', '罐头'] },
      { icon: '🍝', keywords: ['spaghetti', 'pasta', 'yidalimian', '意大利面'] },
      { icon: '🍜', keywords: ['ramen', 'noodle', 'lamian', '拉面'] },
      { icon: '🍲', keywords: ['pot of food', 'huoguo', '火锅'] },
      { icon: '🍛', keywords: ['curry rice', 'gali', '咖喱'] },
      { icon: '🍣', keywords: ['sushi', 'shousi', '寿司'] },
      { icon: '🍱', keywords: ['bento box', 'bian dang', '便当'] },
      { icon: '🥟', keywords: ['dumpling', 'jiaozi', '饺子'] },
      { icon: '🍤', keywords: ['fried shrimp', 'xia', '虾'] },
      { icon: '🍙', keywords: ['rice ball', 'fantuan', '饭团'] },
      { icon: '🍚', keywords: ['cooked rice', 'mifan', '米饭'] },
      { icon: '🍘', keywords: ['rice cracker'] },
      { icon: '🍥', keywords: ['fish cake with swirl'] },
      { icon: '🥠', keywords: ['fortune cookie'] },
      { icon: '🥮', keywords: ['moon cake', 'yuebing', '月饼'] },
      { icon: '🍢', keywords: ['oden'] },
      { icon: '🍡', keywords: ['dango'] },
      { icon: '🍧', keywords: ['shaved ice', 'baobing', '刨冰'] },
      { icon: '🍨', keywords: ['ice cream', 'bingqilin', '冰淇淋'] },
      { icon: '🍦', keywords: ['soft ice cream', 'bingqilin', '冰淇淋'] },
      { icon: '🥧', keywords: ['pie', 'pai', '派'] },
      { icon: '🧁', keywords: ['cupcake'] },
      { icon: '🍰', keywords: ['shortcake', 'dangao', '蛋糕'] },
      { icon: '🎂', keywords: ['birthday cake', 'dangao', '蛋糕'] },
      { icon: '🍮', keywords: ['custard', 'pudding', 'buding', '布丁'] },
      { icon: '🍭', keywords: ['lollipop', 'bangbangtang', '棒棒糖'] },
      { icon: '🍬', keywords: ['candy', 'tang', '糖'] },
      { icon: '🍫', keywords: ['chocolate bar', 'qiaokeli', '巧克力'] },
      { icon: '🍿', keywords: ['popcorn', 'baomihua', '爆米花'] },
      { icon: '🍩', keywords: ['doughnut', 'tianquan', '甜甜圈'] },
      { icon: '🍪', keywords: ['cookie', 'binggan', '饼干'] },
      { icon: '🌰', keywords: ['chestnut', 'lizi', '栗子'] },
      { icon: '🥜', keywords: ['peanuts', 'huasheng', '花生'] },
      { icon: '🍯', keywords: ['honey pot', 'fengmi', '蜂蜜'] },
      { icon: '🥛', keywords: ['glass of milk', 'niunai', '牛奶'] },
      { icon: '🍼', keywords: ['baby bottle', 'naiping', '奶瓶'] },
      { icon: '☕', keywords: ['coffee', 'drink', 'kafei', '咖啡'] },
      { icon: '🍵', keywords: ['teapot', 'tea', 'cha', '茶'] },
      { icon: '🧃', keywords: ['beverage box', 'juice', 'guozhi', '果汁'] },
      { icon: '🥤', keywords: ['cup with straw', 'drink', 'yinliao', '饮料'] },
      { icon: '🍶', keywords: ['sake'] },
      { icon: '🍺', keywords: ['beer mug', 'drink', 'pijiu', '啤酒'] },
      { icon: '🍻', keywords: ['clinking beer mugs', 'cheers', 'ganbei', '干杯'] },
      { icon: '🥂', keywords: ['clinking glasses', 'cheers', 'ganbei', '干杯'] },
      { icon: '🍷', keywords: ['wine glass', 'drink', 'hongjiu', '红酒'] },
      { icon: '🥃', keywords: ['tumbler glass', 'whisky'] },
      { icon: '🍸', keywords: ['cocktail glass'] },
      { icon: '🍹', keywords: ['tropical drink'] },
    ]),
  },
  {
    category: '活动与运动',
    icons: processKeywords([
      { icon: '⚽', keywords: ['soccer ball', 'football', 'zuqiu', '足球'] },
      { icon: '🏀', keywords: ['basketball', 'lanqiu', '篮球'] },
      { icon: '🏈', keywords: ['american football', 'ganlanqiu', '橄榄球'] },
      { icon: '⚾', keywords: ['baseball', 'bangqiu', '棒球'] },
      { icon: '🥎', keywords: ['softball', 'leiqiu', '垒球'] },
      { icon: '🎾', keywords: ['tennis', 'wangqiu', '网球'] },
      { icon: '🏐', keywords: ['volleyball', 'paiqiu', '排球'] },
      { icon: '🏉', keywords: ['rugby football'] },
      { icon: '🥏', keywords: ['flying disc', 'frisbee', 'feipan', '飞盘'] },
      { icon: '🎱', keywords: ['pool 8 ball', 'billiards', 'taiqiu', '台球'] },
      { icon: '🏓', keywords: ['ping pong', 'table tennis', 'pingpangqiu', '乒乓球'] },
      { icon: '🏸', keywords: ['badminton', 'yumaoqiu', '羽毛球'] },
      { icon: '🏒', keywords: ['ice hockey', 'bingqiu', '冰球'] },
      { icon: '🏑', keywords: ['field hockey'] },
      { icon: '🥍', keywords: ['lacrosse'] },
      { icon: '🏏', keywords: ['cricket game'] },
      { icon: '🥅', keywords: ['goal net', 'qiumen', '球门'] },
      { icon: '⛳', keywords: ['golf', 'gaoerfu', '高尔夫'] },
      { icon: '🏹', keywords: ['bow and arrow', 'archery', 'gongjian', '弓箭'] },
      { icon: '🎣', keywords: ['fishing pole', 'diaoyu', '钓鱼'] },
      { icon: '🥊', keywords: ['boxing glove', 'quanji', '拳击'] },
      { icon: '🥋', keywords: ['martial arts uniform', 'judo', 'karate', 'taiquandao', '跆拳道'] },
      { icon: '🎽', keywords: ['running shirt'] },
      { icon: '🛹', keywords: ['skateboard', 'huaban', '滑板'] },
      { icon: '🛷', keywords: ['sled'] },
      { icon: '⛸️', keywords: ['ice skate', 'liubing', '溜冰'] },
      { icon: '🥌', keywords: ['curling stone'] },
      { icon: '🎿', keywords: ['ski', 'huaxue', '滑雪'] },
      { icon: '⛷️', keywords: ['skier', 'huaxue', '滑雪'] },
      { icon: '🏂', keywords: ['snowboarder', 'huaxue', '滑雪'] },
      { icon: '🏋️', keywords: ['person lifting weights', 'gym', 'jianshen', '健身'] },
      { icon: '🤸', keywords: ['person cartwheeling', 'gymnastics', 'ticao', '体操'] },
      { icon: '🤺', keywords: ['person fencing'] },
      { icon: '⛹️', keywords: ['person bouncing ball', 'basketball'] },
      { icon: '🤾', keywords: ['person playing handball'] },
      { icon: '🧗', keywords: ['person climbing', 'panyan', '攀岩'] },
      { icon: '🧘', keywords: ['person in lotus position', 'yoga', 'yujia', '瑜伽'] },
      { icon: '🏄', keywords: ['person surfing', 'chonglang', '冲浪'] },
      { icon: '🏊', keywords: ['person swimming', 'youyong', '游泳'] },
      { icon: '🤽', keywords: ['person playing water polo'] },
      { icon: '🚣', keywords: ['person rowing boat'] },
      { icon: '🏇', keywords: ['horse racing', 'saima', '赛马'] },
      { icon: '🚴', keywords: ['person biking', 'zixingche', '自行车'] },
      { icon: '🚵', keywords: ['person mountain biking'] },
      { icon: '🏅', keywords: ['sports medal', 'jiangpai', '奖牌'] },
      { icon: '🏆', keywords: ['trophy', 'award', 'jiangbei', '奖杯'] },
      { icon: '🥇', keywords: ['1st place medal', 'gold', 'jinpai', '金牌'] },
      { icon: '🥈', keywords: ['2nd place medal', 'silver', 'yinpai', '银牌'] },
      { icon: '🥉', keywords: ['3rd place medal', 'bronze', 'tongpai', '铜牌'] },
      { icon: '🎟️', keywords: ['admission tickets', 'piao', '票'] },
      { icon: '🎫', keywords: ['ticket', 'piao', '票'] },
      { icon: '🎨', keywords: ['artist palette', 'art', 'painting', 'yishu', '艺术', '绘画'] },
      { icon: '🎬', keywords: ['clapper board', 'movie', 'dianying', '电影'] },
      { icon: '🎤', keywords: ['microphone', 'sing', 'huatong', '话筒', '唱歌'] },
      { icon: '🎧', keywords: ['headphone', 'music', 'erji', '耳机', '音乐'] },
      { icon: '🎼', keywords: ['musical score', 'music', 'yuepu', '乐谱'] },
      { icon: '🎹', keywords: ['musical keyboard', 'piano', 'gangqin', '钢琴'] },
      { icon: '🥁', keywords: ['drum', 'gu', '鼓'] },
      { icon: '🎷', keywords: ['saxophone'] },
      { icon: '🎺', keywords: ['trumpet'] },
      { icon: '🎸', keywords: ['guitar', 'jita', '吉他'] },
      { icon: '🪕', keywords: ['banjo'] },
      { icon: '🎻', keywords: ['violin', 'xiaotiqin', '小提琴'] },
      { icon: '🎲', keywords: ['game die', 'dice', 'shaizi', '骰子'] },
      { icon: '♟️', keywords: ['chess pawn', 'xiangqi', '象棋'] },
      { icon: '🎯', keywords: ['direct hit', 'target', 'babiao', '靶标'] },
      { icon: '🎳', keywords: ['bowling', 'baolingqiu', '保龄球'] },
      { icon: '🎮', keywords: ['video game', 'controller', 'youxi', '游戏'] },
      { icon: '🧩', keywords: ['puzzle piece', 'pintu', '拼图'] },
    ]),
  },
  {
    category: '交通与地点',
    icons: processKeywords([
      { icon: '🚗', keywords: ['car', 'auto', 'qiche', '汽车'] },
      { icon: '🚕', keywords: ['taxi', 'chuzuche', '出租车'] },
      { icon: '🚙', keywords: ['jeep', 'suv'] },
      { icon: '🚌', keywords: ['bus', 'gongjiao', '公交'] },
      { icon: '🚎', keywords: ['trolleybus'] },
      { icon: '🏎️', keywords: ['racing car', 'saiche', '赛车'] },
      { icon: '🚓', keywords: ['police car', 'jingche', '警车'] },
      { icon: '🚑', keywords: ['ambulance', 'jiuhuche', '救护车'] },
      { icon: '🚒', keywords: ['fire engine', 'xiaofangche', '消防车'] },
      { icon: '🚐', keywords: ['minibus'] },
      { icon: '🚚', keywords: ['delivery truck', 'huoche', '货车'] },
      { icon: '🚛', keywords: ['articulated lorry', 'huoche', '货车'] },
      { icon: '🚜', keywords: ['tractor', 'tuolaji', '拖拉机'] },
      { icon: '🛴', keywords: ['kick scooter'] },
      { icon: '🚲', keywords: ['bicycle', 'bike', 'zixingche', '自行车'] },
      { icon: '🛵', keywords: ['motor scooter'] },
      { icon: '🏍️', keywords: ['motorcycle', 'motuoche', '摩托车'] },
      { icon: '🛺', keywords: ['auto rickshaw'] },
      { icon: '✈️', keywords: ['airplane', 'flight', 'travel', 'feiji', '飞机', '旅行'] },
      { icon: '🛫', keywords: ['airplane departure', 'takeoff', 'qifei', '起飞'] },
      { icon: '🛬', keywords: ['airplane arrival', 'landing', 'jiangluo', '降落'] },
      { icon: '🚀', keywords: ['rocket', 'space', 'huojian', '火箭'] },
      { icon: '🛸', keywords: ['flying saucer', 'ufo'] },
      { icon: '🚁', keywords: ['helicopter', 'zhishengji', '直升机'] },
      { icon: '🛶', keywords: ['canoe'] },
      { icon: '⛵', keywords: ['sailboat', 'boat', 'chuan', '船'] },
      { icon: '🚤', keywords: ['speedboat'] },
      { icon: '🛥️', keywords: ['motor boat'] },
      { icon: '🛳️', keywords: ['passenger ship', 'cruise', 'youlun', '邮轮'] },
      { icon: '⛴️', keywords: ['ferry', 'boat', 'chuan', '船'] },
      { icon: '🚂', keywords: ['locomotive', 'train', 'huoche', '火车'] },
      { icon: '🚆', keywords: ['train', 'huoche', '火车'] },
      { icon: '🚄', keywords: ['high-speed train', 'bullet train', 'gaotie', '高铁'] },
      { icon: '🚅', keywords: ['bullet train'] },
      { icon: '🚈', keywords: ['light rail'] },
      { icon: '🚇', keywords: ['metro', 'subway', 'ditie', '地铁'] },
      { icon: '🚝', keywords: ['monorail'] },
      { icon: '🚋', keywords: ['tram car'] },
      { icon: '🚃', keywords: ['railway car'] },
      { icon: '🏠', keywords: ['house', 'home', 'jia', '家'] },
      { icon: '🏡', keywords: ['house with garden', 'home', 'jia', '家'] },
      { icon: '🏢', keywords: ['office building', 'work', 'gongsi', '公司'] },
      { icon: '🏣', keywords: ['japanese post office'] },
      { icon: '🏤', keywords: ['post office'] },
      { icon: '🏥', keywords: ['hospital', 'doctor', 'yiyuan', '医院'] },
      { icon: '🏦', keywords: ['bank', 'money', 'yinhang', '银行'] },
      { icon: '🏨', keywords: ['hotel', 'building', 'jiudian', '酒店'] },
      { icon: '🏪', keywords: ['convenience store', 'bianlidian', '便利店'] },
      { icon: '🏫', keywords: ['school', 'xuexiao', '学校'] },
      { icon: '🏬', keywords: ['department store', 'shangchang', '商场'] },
      { icon: '🏭', keywords: ['factory', 'gongchang', '工厂'] },
      { icon: '🏯', keywords: ['japanese castle'] },
      { icon: '🏰', keywords: ['castle', 'chengbao', '城堡'] },
      { icon: '💒', keywords: ['wedding', 'church', 'jiaotang', '教堂'] },
      { icon: '🗼', keywords: ['tokyo tower', 'eiffel', 'tieta', '铁塔'] },
      { icon: '🗽', keywords: ['statue of liberty'] },
      { icon: '⛪', keywords: ['church', 'jiaotang', '教堂'] },
      { icon: '🕌', keywords: ['mosque'] },
      { icon: '🛕', keywords: ['hindu temple'] },
      { icon: '🕍', keywords: ['synagogue'] },
      { icon: '⛩️', keywords: ['shinto shrine'] },
      { icon: '🕋', keywords: ['kaaba'] },
      { icon: '⛲', keywords: ['fountain', 'penquan', '喷泉'] },
      { icon: '⛺', keywords: ['tent', 'camping', 'zhangpeng', '帐篷'] },
      { icon: '🏞️', keywords: ['national park', 'gongyuan', '公园'] },
      { icon: '⛰️', keywords: ['mountain', 'shan', '山'] },
      { icon: '🏔️', keywords: ['snow-capped mountain', 'xueshan', '雪山'] },
      { icon: '🌋', keywords: ['volcano', 'huoshan', '火山'] },
      { icon: '🏜️', keywords: ['desert', 'shamo', '沙漠'] },
      { icon: '🏝️', keywords: ['desert island', 'haidao', '海岛'] },
      { icon: '🏟️', keywords: ['stadium', 'tiyuchang', '体育场'] },
      { icon: '🏗️', keywords: ['building construction', 'jianzhu', '建筑'] },
      { icon: '🏘️', keywords: ['houses', 'shequ', '社区'] },
      { icon: '🏙️', keywords: ['cityscape', 'chengshi', '城市'] },
      { icon: '🌃', keywords: ['night with stars', 'yewan', '夜晚'] },
      { icon: '🌉', keywords: ['bridge at night', 'qiao', '桥'] },
      { icon: '🌌', keywords: ['milky way', 'space', 'yinhe', '银河'] },
    ]),
  },
  {
    category: '健康与医疗',
    icons: processKeywords([
      { icon: '🏃', keywords: ['person running', 'run', 'sport', 'paobu', '跑步', '运动'] },
      { icon: '🚶', keywords: ['person walking', 'walk', 'sanbu', '走路', '散步'] },
      { icon: '🏋️', keywords: ['person lifting weights', 'gym', 'health', 'jianshen', '健身', '健康'] },
      { icon: '💪', keywords: ['flexed biceps', 'strong', 'muscle', 'liliang', '力量', '肌肉'] },
      { icon: '🧠', keywords: ['brain', 'mind', 'intelligent', 'nao', '大脑', '智慧'] },
      { icon: '🦷', keywords: ['tooth', 'dentist', 'yachi', '牙齿'] },
      { icon: '👁️', keywords: ['eye', 'yanjing', '眼睛'] },
      { icon: '👂', keywords: ['ear', 'listen', 'erduo', '耳朵'] },
      { icon: '👃', keywords: ['nose', 'smell', 'bizi', '鼻子'] },
      { icon: '🩸', keywords: ['drop of blood', 'medical', 'xue', '血'] },
      { icon: '❤️‍🩹', keywords: ['mending heart', 'health', 'xiufu', '修复', '健康'] },
      { icon: '🩺', keywords: ['stethoscope', 'doctor', 'medical', 'tingzhenqi', '听诊器'] },
      { icon: '💊', keywords: ['pill', 'medicine', 'drug', 'yao', '药'] },
      { icon: '💉', keywords: ['syringe', 'vaccine', 'medical', 'zhengtong', '针筒', '疫苗'] },
      { icon: '🩹', keywords: ['adhesive bandage', 'band-aid', 'chuangketie', '创可贴'] },
      { icon: '⚕️', keywords: ['medical symbol', 'health', 'yiliao', '医疗'] },
      { icon: '🧬', keywords: ['dna', 'gene', 'jiyin', '基因'] },
      { icon: '🔬', keywords: ['microscope', 'science', 'xianweijing', '显微镜'] },
      { icon: '🧪', keywords: ['test tube', 'science', 'shiguan', '试管'] },
      { icon: '🧼', keywords: ['soap', 'clean', 'feizao', '肥皂'] },
      { icon: '🧽', keywords: ['sponge', 'clean', 'haimian', '海绵'] },
      { icon: '🚑', keywords: ['ambulance', 'emergency', 'jiuhuche', '救护车'] },
      { icon: '🏥', keywords: ['hospital', 'medical', 'yiyuan', '医院'] },
      { icon: '❤️', keywords: ['heart', 'health', 'xin', '心', '健康'] },
      { icon: '🚭', keywords: ['no smoking', 'jinyan', '禁烟'] },
    ]),
  },
]
