/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./components/AnniversaryBanner 2.vue')['default']
    3: typeof import('./components/NoteItem 3.vue')['default']
    4: typeof import('./components/NoteList 4.vue')['default']
    AccountModal: typeof import('./components/AccountModal.vue')['default']
    AnniversaryBanner: typeof import('./components/AnniversaryBanner.vue')['default']
    'AnniversaryBanner_副本': typeof import('./components/AnniversaryBanner_副本.vue')['default']
    AppContainer: typeof import('./components/AppContainer.vue')['default']
    AppProvider: typeof import('./components/AppProvider/index.vue')['default']
    Authentication: typeof import('./components/Authentication.vue')['default']
    'Authentication_副本': typeof import('./components/Authentication_副本.vue')['default']
    Blank: typeof import('./components/Blank.vue')['default']
    CalendarView: typeof import('./components/CalendarView.vue')['default']
    DateTimePickerModal: typeof import('./components/DateTimePickerModal.vue')['default']
    MobileDateRangePicker: typeof import('./components/MobileDateRangePicker.vue')['default']
    'MobileDateRangePicker_副本': typeof import('./components/MobileDateRangePicker_副本.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NoteActions: typeof import('./components/NoteActions.vue')['default']
    'NoteActions_副本': typeof import('./components/NoteActions_副本.vue')['default']
    NoteEditor: typeof import('./components/NoteEditor.vue')['default']
    'NoteEditor_副本': typeof import('./components/NoteEditor_副本.vue')['default']
    NoteItem: typeof import('./components/NoteItem.vue')['default']
    'NoteItem_副本': typeof import('./components/NoteItem_副本.vue')['default']
    NoteItemSkeleton: typeof import('./components/NoteItemSkeleton.vue')['default']
    'NoteItemSkeleton_副本': typeof import('./components/NoteItemSkeleton_副本.vue')['default']
    NoteList: typeof import('./components/NoteList.vue')['default']
    'NoteList_副本': typeof import('./components/NoteList_副本.vue')['default']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
    TestEditor: typeof import('./components/TestEditor.vue')['default']
    TheDoc: typeof import('./components/TheDoc.vue')['default']
    TheFooter: typeof import('./components/TheFooter/index.vue')['default']
    TrashModal: typeof import('./components/TrashModal.vue')['default']
    WeatherTest: typeof import('./components/WeatherTest.vue')['default']
  }
}
