/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountModal: typeof import('./components/AccountModal.vue')['default']
    AnniversaryBanner: typeof import('./components/AnniversaryBanner.vue')['default']
    AppContainer: typeof import('./components/AppContainer.vue')['default']
    AppProvider: typeof import('./components/AppProvider/index.vue')['default']
    Authentication: typeof import('./components/Authentication.vue')['default']
    Blank: typeof import('./components/Blank.vue')['default']
    CalendarView: typeof import('./components/CalendarView.vue')['default']
    DateTimePickerModal: typeof import('./components/DateTimePickerModal.vue')['default']
    MobileDateRangePicker: typeof import('./components/MobileDateRangePicker.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NoteActions: typeof import('./components/NoteActions.vue')['default']
    NoteEditor: typeof import('./components/NoteEditor.vue')['default']
    NoteItem: typeof import('./components/NoteItem.vue')['default']
    NoteItemSkeleton: typeof import('./components/NoteItemSkeleton.vue')['default']
    NoteList: typeof import('./components/NoteList.vue')['default']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
    TheDoc: typeof import('./components/TheDoc.vue')['default']
    TheFooter: typeof import('./components/TheFooter/index.vue')['default']
    TrashModal: typeof import('./components/TrashModal.vue')['default']
  }
}
