name: Daily PWA Notify (11:30 PT)

on:
  # 每 5 分钟跑一次，用本地时区判断是否为 11:20；避免夏令时切换问题
  schedule:
    - cron: '*/5 * * * *'
  # 可手动触发，便于立刻测试
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      # 设置想要的“本地时区”为洛杉矶
      TZ: America/Los_Angeles
    steps:
      - name: Check time window
        id: gate
        run: |
          NOW="$(date +'%H:%M')"
          echo "Local time (PT): $NOW"
          if [ "$NOW" = "11:30" ]; then
            echo "run=1" >> $GITHUB_OUTPUT
          else
            echo "run=0" >> $GITHUB_OUTPUT
          fi

      - name: Call send-notification
        if: steps.gate.outputs.run == '1' || github.event_name == 'workflow_dispatch'
        run: |
          curl -i -sS -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE }}" \
            -d '{}' \
            "${{ secrets.SUPABASE_FUNCTION_URL }}"
